import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="p-5 flex justify-center gap-5">
            <Link href="/about" className="bg-slate-200 p-3 rounded-md">
              About
            </Link>
            <Link href="/todo" className="bg-slate-200 p-3 rounded-md">
              Todo
            </Link>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
